module.exports = {
	products: [
		{
			_id: '1',
			name: 'yoga mat sport',
			category: 'mat',
			image: '/images/product-1.jpg',
			price: 1999,
			brand: 'M2',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '2',
			name: 'Mat Colchoneta Yoga Caucho Natural 4 Mm Guia De Posiciones',
			category: 'mat',
			image: '/images/product-2.jpg',
			price: 2490,
			brand: 'Alitrade',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '3',
			name: 'Mat Yoga Mat 6mm Tpe Importadas Con Bolso - Ecologico',
			category: 'mat',
			image: '/images/product-3.jpg',
			price: 2499,
			brand: 'hippie sport',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '4',
			name: 'Colchoneta Mat Yoga Pilates Enrollable',
			category: 'mat',
			image: '/images/product-4.jpg',
			price: 1499,
			brand: 'Mercado Libre Basics',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '5',
			name: 'Yoga Mat Colchoneta 6mm Pvc Pilates Fitness Gym 183cm X 61cm',
			category: 'mat',
			image: '/images/product-5.jpg',
			price: 1889,
			brand: 'Pilates Fitness',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '6',
			name: 'Colchoneta Yoga Tpe Doble Capa Gym Fitness Pilates +bolso',
			category: 'mat',
			image: '/images/product-6.jpg',
			price: 3180,
			brand: 'Deco Estrella',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '7',
			name: 'Colchoneta Mat Yoga Fitnes Pilates 6mm Estampada Impor Elrey',
			category: 'mat',
			image: '/images/product-7.jpg',
			price: 1890,
			brand: 'Deco Estrella',
			numReviews: 10,
			countInStock: 6,
    },
    {
			_id: '8',
			name: 'Mat De Yoga 6mm / Estampado Reversible / Gaiam #1 Usa / Eco',
			category: 'mat',
			image: '/images/product-8.jpg',
			price: 59.99,
			brand: 'Gaiam',
			numReviews: 10,
			countInStock: 6,
		}
	]
}